apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: sarushop
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3A=
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: sarushop 
  labels:
    name: rabbitmq
    project: sarushop
    tier: db 
spec:
  replicas: 1
  selector:
    matchLabels: # should match with pod
      name: rabbitmq
      project: sarushop
      tier: db
  template: # pod defination
    metadata:
      labels: # pod labels
        name: rabbitmq
        project: sarushop
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: sarushop
spec:
  selector:
    name: rabbitmq
    project: sarushop
    tier: db 
  ports:
  - protocol: TCP
    port: 5672 #service-port
    targetPort: 5672 #container-port
