apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: sarushop
data:
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: sarushop 
  labels:
    name: catalogue
    project: sarushop
    tier: app 
spec:
  replicas: 1
  selector:
    matchLabels: # deployment-set labels
      name: catalogue
      project: sarushop
      tier: app
  template: # pod defination
    metadata:
      labels: # pod labels
        name: catalogue
        project: sarushop
        tier: app
    spec:
      containers:
      - name: catalogue
        image: iamroyalreddy/catalogue:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: sarushop
spec:
  selector:
    name: catalogue
    project: sarushop
    tier: app 
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port
