apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: sarushop
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: sarushop
  labels: # these labels are deployment labels
    app: payment
    project: sarushop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: payment
      project: sarushop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: payment
        project: sarushop
        tier: app
    spec:
      containers:
      - name: payment
        image: joindevops/payment:v1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: sarushop
spec:
  selector:
    app: payment
    project: sarushop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port