apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-test
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-061cb5c565c9c7968