apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sarushop-ebs
reclaimPolicy: Retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer #storage will created pod will be created 