apiVersion: v1
kind: PersistentVolume
metadata:
  name: sarushop-efs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0bb3161d74c9341e0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sarushop-efs
spec:
  volumeName: sarushop-efs
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: static-efs
  labels:
    purpose: static-efs
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v hostpath:contaierpath
    - name: sarushop-efs
      mountPath: /usr/share/nginx/html
  volumes:
  - name: sarushop-efs
    persistentVolumeClaim:
      claimName: sarushop-efs
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: static-efs
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30007
