kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sarushop-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  directoryPerms: "700"
  fileSystemId: fs-0bb3161d74c9341e0
  basePath: "/sarushop"